name: 'DB:SQLServer'
permissions: {}

on: workflow_call

jobs:
  # Label of the container job
  test-sqlserver:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: npm install, build, and test
        run: |
          npm ci --loglevel error
          npm run build
          tar -xzvf test/data/sqlserver/malloytest-sqlserver.tar.gz
          ./test/mysql/sqlserver_start.sh
          npx jest --reporters jest-silent-reporter --reporters summary --config jest.sqlserver.config.ts
          ./test/sqlserver/sqlserver_stop.sh
        env:
          MALLOY_DATABASES: mysql
          SQLSERVER_USER: SA
          SQLSERVER_HOST: localhost
          SQLSERVER_PORT: 1433
          SQLSERVER_PASSWORD: saTEST_0pword
          SQLSERVER_DATABASE: malloytestdb
          SQLSERVER_SCHEMA: malloytest
          SQLSERVER_ENCRYPT: true
          SQLSERVER_TRUST_SERVER_CERTIFICATE: true
